# Generated by Django 6.0.7 on 2026-08-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_savedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
