# Generated by Django 6.1 on 2026-08-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
