# Generated by Django 6.1 on 2026-08-14 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
        ('posts', '0009_post_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['community', '-is_pinned', '-created_at'], name='posts_post_communi_17396e_idx'),
        ),
    ]
