# Generated by Django 6.0.7 on 2026-08-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-is_accepted', 'created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
