# Generated by Django 6.1 on 2026-08-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
