# Generated by Django 6.0.7 on 2026-08-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_is_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='join_mode',
            field=models.CharField(choices=[('open', 'Open — join instantly'), ('approval', 'Registration required — an admin must approve')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending approval')], default='approved', max_length=20),
        ),
    ]
