# Generated by Django 6.0.7 on 2026-09-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_join_mode_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('education', 'Education'), ('social', 'Social'), ('gaming', 'Gaming'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='community',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='community_covers/'),
        ),
        migrations.AddField(
            model_name='community',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='community',
            name='member_count_boost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
