# Generated by Django 6.0.7 on 2026-08-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_read_at'),
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='circles.circle'),
        ),
    ]
