# Generated by Django 6.1 on 2026-08-14 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_circle'),
        ('circles', '0003_circleevent_circleeventrsvp_circleevent_rsvps'),
        ('communities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'read_at'], name='chat_messag_recipie_aa591b_idx'),
        ),
    ]
