# Generated by Django 6.0.7 on 2026-08-31 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_chat_messag_recipie_aa591b_idx'),
        ('circles', '0003_circleevent_circleeventrsvp_circleevent_rsvps'),
        ('communities', '0003_community_is_on_hold'),
        ('posts', '0012_alter_comment_options_comment_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='circles.circle'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='communities.community'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='posts.post'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='circles.circlequestion'),
        ),
    ]
