# Generated by Django 6.0.7 on 2026-08-31 04:48, hand-edited to be safe to
# re-run against a database that already has these columns.
#
# Why: this project went through two parallel edits of chat/models.py that
# both independently added the same shared_post/shared_question/
# shared_community/shared_circle fields, under two different migration
# numbers. If one of those was ever applied to a database (even from a
# build that failed on a later step), Django's plain AddField operations
# below would blow up with "column already exists" on a second apply,
# because AddField always emits an unconditional ALTER TABLE ADD COLUMN.
#
# Each field is added only if the column isn't already there, so this is
# safe to run against a fresh database AND a database that already has
# some/all of these columns from an earlier deploy.
import django.db.models.deletion
from django.db import migrations, models


def _existing_columns(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return {
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        }


def add_shared_fields(apps, schema_editor):
    Message = apps.get_model('chat', 'Message')
    Post = apps.get_model('posts', 'Post')
    CircleQuestion = apps.get_model('circles', 'CircleQuestion')
    Community = apps.get_model('communities', 'Community')
    Circle = apps.get_model('circles', 'Circle')

    table_name = Message._meta.db_table
    existing = _existing_columns(schema_editor, table_name)

    field_defs = [
        ('shared_post', Post),
        ('shared_question', CircleQuestion),
        ('shared_community', Community),
        ('shared_circle', Circle),
    ]
    for field_name, target_model in field_defs:
        field = models.ForeignKey(
            target_model, on_delete=models.SET_NULL, null=True, blank=True,
            related_name='shared_in_messages',
        )
        field.set_attributes_from_name(field_name)
        if field.column in existing:
            # Already there (from an earlier partial/duplicate deploy) —
            # skip the ALTER TABLE, Django's migration state still gets
            # marked as applied so future migrations see the field as
            # present.
            continue
        schema_editor.add_field(Message, field)


def remove_shared_fields(apps, schema_editor):
    Message = apps.get_model('chat', 'Message')
    Post = apps.get_model('posts', 'Post')
    CircleQuestion = apps.get_model('circles', 'CircleQuestion')
    Community = apps.get_model('communities', 'Community')
    Circle = apps.get_model('circles', 'Circle')

    table_name = Message._meta.db_table
    existing = _existing_columns(schema_editor, table_name)

    field_defs = [
        ('shared_post', Post),
        ('shared_question', CircleQuestion),
        ('shared_community', Community),
        ('shared_circle', Circle),
    ]
    for field_name, target_model in field_defs:
        field = models.ForeignKey(
            target_model, on_delete=models.SET_NULL, null=True, blank=True,
            related_name='shared_in_messages',
        )
        field.set_attributes_from_name(field_name)
        if field.column not in existing:
            continue
        schema_editor.remove_field(Message, field)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_chat_messag_recipie_aa591b_idx'),
        ('circles', '0003_circleevent_circleeventrsvp_circleevent_rsvps'),
        ('communities', '0003_community_is_on_hold'),
        ('posts', '0012_alter_comment_options_comment_is_accepted'),
    ]

    operations = [
        # SeparateDatabaseAndState: the *state* side (what Django believes
        # the Message model looks like after this migration) is still the
        # normal four AddField ops, so makemigrations/serializers/admin
        # etc. all behave exactly as before. Only the *database* side is
        # replaced with the existence-checking RunPython above.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='message',
                    name='shared_circle',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='circles.circle'),
                ),
                migrations.AddField(
                    model_name='message',
                    name='shared_community',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='communities.community'),
                ),
                migrations.AddField(
                    model_name='message',
                    name='shared_post',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='posts.post'),
                ),
                migrations.AddField(
                    model_name='message',
                    name='shared_question',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='circles.circlequestion'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_shared_fields, remove_shared_fields),
            ],
        ),
    ]
