# Generated by Django 6.1 on 2026-08-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('post_liked', 'liked your post'), ('comment_liked', 'liked your comment'), ('post_commented', 'commented on your post'), ('comment_replied', 'replied to your comment'), ('community_joined', 'joined your community'), ('verification_approved', 'your verification was approved'), ('verification_rejected', 'your verification was rejected'), ('new_follower', 'started following you'), ('follow_requested', 'requested to follow you'), ('follow_accepted', 'accepted your follow request'), ('circle_invited', 'invited you to a circle'), ('circle_invite_accepted', 'accepted your circle invite'), ('circle_question_answered', 'answered your question'), ('circle_answer_accepted', 'accepted your answer'), ('circle_event_created', 'scheduled an event in a circle')], max_length=30),
        ),
    ]
